twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        openingHours: '@App\Twig\OpeningHoursExtension'
        comments: '@App\Twig\CommentsExtension'

when@test:
    twig:
        strict_variables: true
